/*
CREATE INDEX >>> COMMAND THAT CREATES AN INDEX ON THE BASIS
OF SELECTED ATTRIBUTE(S)

CREATE INDEX index ON table(column1, column2);

CREATE UNIQUE INDEX index ON table(column1, column2); 
*/

CREATE INDEX P_INDATE_X ON PRODUCT(P_INDATE);

CREATE UNIQUE INDEX P_DESCRIPTION_X ON PRODUCT(P_DESCRIPTION);

CREATE INDEX P_PRICE_X ON PRODUCT(P_PRICE DESC);