/*
UPDATE >>> COMMAND THAT ALLOWS ATTRIBUTE VALUES TO BE
CHANGED IN ONE OR MORE ROWS OF A TABLE

WHERE >>> CLAUSE THAT ADDS CONDITIONAL RESTRICTIONS TO 
A COMMAND AND LIMITS THE ROWS RETURNED BY A SELECT OR 
AFFECTED BY AN UPDATE

UPDATE table
SET column1 = value1, column2 = value2;

NOTE ELIMINATING THE WHERE CLAUSE WILL UPDATE ALL 
VALUES FOR THE COLUMN IN THE ENTIRE TABLE

UPDATE table
SET column1 = value1, column2 = value2
WHERE condition1, condition2, condition3;

NOTE ADDING THE WHERE CLAUSE WILL UPDATE ONLY 
THE VALUES FOR THE RECORDS THAT MATCH THE SPECIFIED
CRITERIA
*/

UPDATE PRODUCT
SET P_INDATE = '18-JAN-2016'
WHERE P_CODE = '13-Q2/P2';

COMMIT;


UPDATE PRODUCT
SET P_INDATE = '20-JAN-2016', P_PRICE = 17.99, P_MIN = 10
WHERE P_CODE = '13-Q2/P2';

COMMIT;