/*
ROLLBACK >>> COMMAND THAT RESTORES THE DATABASE TABLE
CONTENTS TO THE CONDITION THAT EXISTED AFTER THE LAST COMMIT 
STATEMENT

***NOTE THE ROLLBACK COMMAND ONLY PERFORMS AN "UNDO" FOR THE 
INSERT AND UPDATE DML COMMANDS (NOT THE DDL COMMANDS)

ROLLBACK;

*/
CREATE TABLE SALES(
    S_CODE NUMBER PRIMARY KEY,
    S_LNAME VARCHAR(15) NOT NULL,
    S_FNAME VARCHAR(15) NOT NULL,
    S_INITIAL CHAR(1),
    S_AREACODE CHAR(3) DEFAULT '717' NOT NULL CHECK(S_AREACODE IN ('717', '818', '919')),
    S_PHONE CHAR(8) NOT NULL,
    S_HIRE_DATE DATE
);

INSERT INTO SALES VALUES('1', 'Smith', 'John', NULL, '717', '555-1234', '11-MAR-2018');

INSERT INTO SALES VALUES('2', 'Myers', 'Beth', NULL, '717', '555-5678', '09-MAR-2018');

INSERT INTO SALES VALUES('3', 'Turner', 'Bill', NULL, '717', '555-9876', '01-MAR-2018');

SELECT * FROM SALES;

UPDATE SALES
SET S_AREACODE = '818';

SELECT * FROM SALES;

UPDATE SALES
SET S_HIRE_DATE = '01-JAN-2018' 
WHERE S_CODE = 1;

SELECT * FROM SALES;

ROLLBACK;

SELECT * FROM SALES;