/*
DELETE >>> COMMAND THAT ALLOWS DATA ROWS TO 
BE DELETED FROM A TABLE

DELETE FROM table;

NOTE ELIMINATING THE WHERE CLAUSE WILL 
DELETE ALL DATA IN THE ENTIRE TABLE

DELETE FROM table
WHERE condition;

NOTE ADDING THE WHERE CLAUSE WILL DELETE DATA
ONLY FOR THE RECORDS THAT MATCH THE SPECIFIED
CRITERIA
*/

DELETE FROM SALES;

INSERT INTO SALES VALUES('1', 'Smith', 'John', NULL, '717', '555-1234', '11-MAR-2018');

INSERT INTO SALES VALUES('2', 'Myers', 'Beth', NULL, '717', '555-5678', '09-MAR-2018');

INSERT INTO SALES VALUES('3', 'Turner', 'Bill', NULL, '717', '555-9876', '01-MAR-2018');

DELETE FROM SALES
WHERE S_CODE = 1;

DELETE FROM SALES
WHERE S_LNAME = 'Turner';

SELECT * FROM SALES;