/*
LOGICAL OPERATORS:
OR >>> USED TO LINK MULTIPLE CONDITIONAL EXPRESSIONS
IN A WHERE OR HAVING CLAUSE; IT REQUIRES ONLY ONE OF 
THE CONDITIONAL EXPRESSIONS TO BE TRUE

AND >>> USED TO LINK MULTIPLE CONDITIONAL EXPRESSIONS
IN A WHERE OR HAVING CLAUSE; IT REQUIRES ALL OF THE 
CONDITIONAL EXPRESSIONS TO BE TRUE

NOT >>> NEGATES A GIVEN PREDICATE
*/

SELECT P_DESCRIPTION, P_INDATE, P_PRICE, V_CODE
FROM PRODUCT
WHERE V_CODE = 21225 OR V_CODE = 24288;

SELECT *
FROM PRODUCT
WHERE P_PRICE < 50
AND P_INDATE > '15-Jan-2016';

SELECT *
FROM PRODUCT
WHERE (P_PRICE < 50 AND P_INDATE > '15-Jan-2016')
OR V_CODE = 24288;

SELECT *
FROM PRODUCT
WHERE NOT(V_CODE = 24288);

SELECT *
FROM PRODUCT
WHERE V_CODE <> 24288;

SELECT *
FROM PRODUCT
WHERE V_CODE != 24288;