/*
CREATE TABLE >>> COMMAND THAT CREATES A TABLE STRUCTURE
USING THE CHARACTERISTICS AND ATTRIBUTES PROVIDED 

CREATE TABLE table(
    column1 datatype constraint,
    column2 datatype constraint,
    column3 datatype constraint,
    PRIMARY KEY(column1, column2),
    FOREIGN KEY(column1, column2) REFERENCES table,
    CONSTRAINT constraint
);
*/

CREATE TABLE VENDOR(
    V_CODE INTEGER PRIMARY KEY,
    V_NAME VARCHAR(35) NOT NULL,
    V_CONTACT VARCHAR(25) NOT NULL,
    V_AREACODE CHAR(3) NOT NULL,
    V_PHONE CHAR(8) NOT NULL,
    V_STATE CHAR(2) NOT NULL,
    V_ORDER CHAR(1) NOT NULL
);

CREATE TABLE PRODUCT(
    P_CODE VARCHAR(10) PRIMARY KEY,
    P_DESCRIPTION VARCHAR(35) NOT NULL,
    P_INDATE DATE NOT NULL,
    P_QOH SMALLINT NOT NULL,
    P_MIN SMALLINT NOT NULL,
    P_PRICE NUMBER(8,2) NOT NULL,
    P_DISCOUNT NUMBER(5,2) NOT NULL,
    V_CODE INTEGER,
    FOREIGN KEY(V_CODE) REFERENCES VENDOR 
);

CREATE TABLE CUSTOMER(
    C_CODE NUMBER PRIMARY KEY,
    C_LNAME VARCHAR(15) NOT NULL,
    C_FNAME VARCHAR(15) NOT NULL,
    C_INITIAL CHAR(1),
    C_AREACODE CHAR(3) DEFAULT '717' NOT NULL CHECK(C_AREACODE IN ('717', '818', '919')),
    C_PHONE CHAR(8) NOT NULL,
    C_BALANCE NUMBER(9,2) DEFAULT 0.00,
    CONSTRAINT C_UI1 UNIQUE(C_LNAME, C_FNAME)
);

CREATE TABLE INVOICE(
    I_NUM NUMBER PRIMARY KEY,
    C_CODE NUMBER NOT NULL REFERENCES CUSTOMER(C_CODE),
    I_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT I_CK1 CHECK(I_DATE > TO_DATE('01-JAN-2016', 'DD-MON-YYYY'))
);

CREATE TABLE LINE(
    I_NUM NUMBER NOT NULL,
    L_NUM NUMBER(2,0) NOT NULL,
    P_CODE VARCHAR(10) NOT NULL,
    L_UNITS NUMBER(9,2) DEFAULT 0.00 NOT NULL,
    L_PRICE NUMBER(9,2) DEFAULT 0.00 NOT NULL,
    PRIMARY KEY(I_NUM, L_NUM),
    FOREIGN KEY(I_NUM) REFERENCES INVOICE,
    FOREIGN KEY(P_CODE) REFERENCES PRODUCT(P_CODE),
    CONSTRAINT L_UI1 UNIQUE(I_NUM, P_CODE)
);