/*
ALTER >>> COMMAND USED TO MAKE CHANGES TO A TABLE 
STRUCTURE

ALTER TABLE table
ADD column1 datatype;

ALTER TABLE table
DROP COLUMN column;

ALTER TABLE table
MODIFY column datatype;
*/

/*
SHOWS COLUMNS P_CODE, P_DESCRIPTION, P_INDATE, P_QOH
P_MIN, P_PRICE, P_DISCOUNT AND V_CODE
*/
SELECT * FROM PRODUCT; 

ALTER TABLE PRODUCT
ADD(P_SALECODE CHAR(1));

/*SHOW COLUMNS P_CODE, P_DESCRIPTION, P_INDATE, P_QOH
P_MIN, P_PRICE, P_DISCOUNT, V_CODE, AND P_SALECODE
*/
SELECT * FROM PRODUCT; 



/*
SHOWS COLUMNS V_CODE, V_NAME, V_CONTACT, V_AREACODE, 
V_PHONE, V_STATE AND V_ORDER
*/
SELECT * FROM VENDOR;

ALTER TABLE VENDOR
DROP COLUMN V_ORDER;

/*
SHOWS COLUMNS V_CODE, V_NAME, V_CONTACT, V_AREACODE, 
V_PHONE, AND V_STATE
*/
SELECT * FROM VENDOR;



ALTER TABLE PRODUCT
MODIFY P_CODE VARCHAR(15);

ALTER TABLE PRODUCT
MODIFY P_PRICE DECIMAL(9,2);