/*
ALTER >>> COMMAND USED TO MAKE CHANGES TO A TABLE'S
STRUCTURE

ALTER TABLE table
ADD PRIMARY KEY(column1, column2);

ALTER TABLE table
ADD FOREIGN KEY(column1) REFERENCES foreign_table1
AND FOREIGN KEY(column2) REFERENCES foreign_table2;
*/

ALTER TABLE PART
ADD PRIMARY KEY(PT_CODE);

ALTER TABLE PART
ADD FOREIGN KEY(V_CODE) REFERENCES VENDOR;

