/*
DISTINCT >>> CLAUSE THAT PRODUCES ONLY A LIST OF
VALUES THAT ARE DIFFERENT FROM ONE ANOTHER

SELECT DISTINCT column
FROM table;
*/

SELECT * 
FROM PRODUCT;

SELECT DISTINCT P_PRICE
FROM PRODUCT;

SELECT DISTINCT P_CODE, P_PRICE
FROM PRODUCT;