/*
COUNT >>> # OF ROWS CONTAINING NON-NULL VALUES

MIN >>> MINIMUM ATTRIBUTE VALUE ENCOUNTERED IN A GIVEN COLUMN

MAX >>> MAXIMUM ATTRIBUTE VALUE ENCOUNTERED IN A GIVEN COLUMN

SUM >>> SUM OF ALL VALUES FOR A GIVEN COLUMN

AVG >>> AVERAGE (MEAN) FOR A SPECIFIED COLUMN

SELECT COUNT(column)
FROM table
WHERE condition;

SELECT COUNT(DISTINCT column)
FROM table
WHERE condition;

SELECT MIN(column)
FROM table
WHERE condition;

SELECT MAX(column)
FROM table
WHERE condition;

SELECT SUM(column)
FROM table
WHERE condition;

SELECT AVG(column)
FROM table
WHERE condition;
*/

SELECT COUNT(DISTINCT V_CODE)
FROM PRODUCT;

SELECT MIN(P_PRICE)
FROM PRODUCT
WHERE P_PRICE >= 50.00;

SELECT MAX(P_PRICE)
FROM PRODUCT;

SELECT SUM(P_PRICE) AS TOTAL_VALUE
FROM PRODUCT;

SELECT AVG(P_PRICE) AS PRICE_AVG
FROM PRODUCT;