/*
GROUP BY >>> CLAUSE USED TO CREATE FREQUENCY
DISTRIBUTIONS WHEN COMBINED WITH ANY OF THE 
AGGREGATE FUNCTIONS IN A SELECT QUERY

*NOTE: GROUP BY MUST BE USED WITH AN AGGREGATE
FUNCTION (AVG, MIN, MAX, COUNT, ETC.)

HAVING >>> CLAUSE APPLIED TO THE OUTPUT OF A 
GROUP BY OPERATION TO RESTRICT SELECTED ROWS

ORDER BY >>> CLAUSE USED TO ORDER THE OUTPUT
OF A SELECT QUERY IN EITHER ASCENDING (ASC)
OR DESCENDING (DESC) ORDER

SELECT columns
FROM table
WHERE conditions
GROUP BY columns

SELECT columns
FROM table
WHERE conditions
GROUP BY columns
HAVING conditions
ORDER BY columns;
*/

SELECT P_SALECODE, MIN(P_PRICE)
FROM PRODUCT
GROUP BY P_SALECODE
ORDER BY P_SALECODE;

SELECT V_CODE, COUNT(P_CODE), AVG(P_PRICE)
FROM PRODUCT
GROUP BY V_CODE
ORDER BY V_CODE;

SELECT V_CODE, COUNT(P_CODE), AVG(P_PRICE)
FROM PRODUCT
GROUP BY V_CODE
HAVING AVG(P_PRICE) < 10
ORDER BY V_CODE;

SELECT V_CODE, SUM(P_QOH * P_PRICE) AS TOTAL_COST
FROM PRODUCT
GROUP BY V_CODE
HAVING (SUM(P_QOH * P_PRICE) > 500)
ORDER BY SUM(P_QOH * P_PRICE) DESC;