/*
JOIN >>> RETRIEVING DATA FROM MORE THAN ONE TABLE 
AT A TIME

ALIAS >>> USED TO IDENTIFY THE SOURCE TABLE FROM WHICH 
DATA IS TAKEN

RECURSIVE JOIN >>> USED WHEN A TABLE MUST BE JOINED TO 
ITSELF.

LIST THE TABLES IN THE FROM CLAUSE OF THE SELECT. BY
DEFAULT THE DATABASE WILL JOIN THE RECORDS FROM BOTH 
TABLES IN ALL POSSIBLE COMBINATIONS (CARTESIAN JOIN).
TO REMOVE THE CARTESIAN JOIN THE TABLES MUST BE JOINED 
ON A COMMON ATTRIBUTE TO FIND ONLY MATCHING RECORDS 
BETWEEN THE TABLES, WHICH IS USUALLY DONE IN THE WHERE
CLAUSE OF THE STATEMENT.

SELECT table1.column1, table1.column2, table1.column3, table2.column2, table2.column3
FROM table1, table2
WHERE table1.column1 = table2.column1
AND conditions;

SELECT t1.column1, t1.column2, t1.column3, t2.column2, t2.column3
FROM table1 t1, table2 t2
WHERE t1.column1 = t2.column1
AND conditions;

*NOTE: t1 and t2 are aliases for tables tabel1 and table2, respectively.
*/

SELECT *
FROM PRODUCT;

SELECT *
FROM VENDOR;

SELECT PRODUCT.P_DESCRIPTION, 
    PRODUCT.P_PRICE, 
    VENDOR.V_NAME, 
    VENDOR.V_CONTACT, 
    VENDOR.V_AREACODE, 
    VENDOR.V_PHONE
FROM PRODUCT, VENDOR
WHERE PRODUCT.V_CODE = VENDOR.V_CODE;

SELECT PRODUCT.P_DESCRIPTION, 
    PRODUCT.P_PRICE, 
    VENDOR.V_NAME, 
    VENDOR.V_CONTACT, 
    VENDOR.V_AREACODE, 
    VENDOR.V_PHONE
FROM PRODUCT, VENDOR
WHERE PRODUCT.V_CODE = VENDOR.V_CODE
AND P_INDATE > TO_DATE('15-JAN-2016', 'DD-MON-YYYY');

SELECT CUSTOMER.C_LNAME, INVOICE.I_NUM, INVOICE.I_DATE, PRODUCT.P_DESCRIPTION
FROM CUSTOMER, INVOICE, LINE, PRODUCT 
WHERE CUSTOMER.C_CODE = INVOICE.C_CODE
AND LINE.P_CODE = PRODUCT.P_CODE
AND CUSTOMER.C_CODE = 10014
ORDER BY INVOICE.I_NUM;

SELECT P.P_DESCRIPTION, 
    P.P_PRICE, 
    V.V_NAME, 
    V.V_CONTACT, 
    V.V_AREACODE, 
    V.V_PHONE
FROM PRODUCT P, VENDOR V
WHERE P.V_CODE = V.V_CODE
ORDER BY P.P_PRICE;