/*
BATCH UPDATE ROUTINE >>> POOLS TRANSACTIONS INTO A SINGLE GROUP TO
                         UPDATE A MASTER TABLE IN A SINGLE OPERATION     
                         
UPDATABLE VIEW >>> A VIEW THAT CAN UPDATE ATTRIBUTES IN BASE TABLES THAT 
                   ARE USED IN THE VIEW                         
*/

CREATE VIEW PSVUPD AS
    SELECT PRODMASTER.PROD_ID, PROD_QOH, PS_QTY
    FROM PRODMASTER, PRODSALES
    WHERE PRODMASTER.PROD_ID = PRODSALES.PROD_ID;

SELECT *
FROM PRODMASTER;

SELECT *
FROM PRODSALES;

UPDATE PSVUPD
SET PROD_QOH = PROD_QOH - PS_QTY;

SELECT * FROM PRODMASTER;