/*
PROCEDURAL LANGUAGE SQL (PL/SQL) >>> ORACLE-SPECIFIC PROGRAMMING LANGUAGE BASED ON SQL WITH 
                                     PROCEDURAL EXTENSIONS DESIGNED TO RUN INSIDE THE ORACLE 
                                     DATABASE
                                     
FUNCTION >>> NAMED GROUP OF PROCEDURAL AND SQL STATEMENTS THAT RETURNS A VALUE, AS INDICATED BY
             A RETURN STATEMENT IN ITS PROGRAM CODE
           
CREATE FUNCTION function (argument IN data type) RETURN data type IS
BEGIN
    PL/SQL statements;
    RETURN value/expression;
END;    
*/

CREATE OR REPLACE FUNCTION FNC_PROD_TOT_VALUE RETURN PRODUCT.P_PRICE%TYPE IS
    W_TOT PRODUCT.P_PRICE%TYPE;
BEGIN
    SELECT SUM(P_PRICE) INTO W_TOT
    FROM PRODUCT;
    
    IF W_TOT > 0 THEN
        RETURN W_TOT;
    ELSE
        RETURN 0.00;
    END IF;
END;