/*
SELECT >>> COMMAND THAT YIELDS THE VALUES OF ALL ROWS OR
A SUBSET OF ROWS IN A TABLE; USED TO RETRIEVE DATA FROM TABLES

FROM >>> CLAUSE THAT SPECIFIES THE TABLE(S) FROM WHICH DATA IS 
TO BE RETRIEVED

WILDCARD >>> SYMBOL THAT CAN BE USED AS A GENERAL SUBSTITUTE FOR
ALL COLUMNS IN A TABLE (*) WHEN USED IN AN ATTRIBUTE LIST OF
A SELECT STATEMENT

WHERE >>> CLAUSE THAT ADDS CONDITIONAL RESTRICTIONS TO 
A COMMAND AND LIMITS THE ROWS RETURNED BY A SELECT OR 
AFFECTED BY AN UPDATE

NOTE THE ASTERISK (*) IS USED AS A WILDCARD TO BRING BACK ALL OF 
THE COLUMNS IN A TABLE WITHOUT HAVING TO LIST EACH INDIVIDUALLY

COMPARISON OPERATORS:
EQUAL TO (=)
LESS THAN (<)
LESS THAN OR EQUAL TO (<=)
GREATER THAN (>)
GREATER THAN OR EQUAL TO (>=)
NOT EQUAL TO (<> OR !=)

ARITHMETIC OPERATORS:
ADD (+)
SUBTRACT (-)
MULTIPLY (*)
DIVIDE (/)
RAISE TO THE POWER OF (^)

SELECT column1, column2, column3
FROM table
WHERE condition1, condition2, condition3;
*/

INSERT INTO PRODUCT VALUES('14-Q1/L3', '9.00-in. pwr. saw blade', '11-Mar-2018', 18, 12, 17.49, 0.00, NULL);
INSERT INTO PRODUCT VALUES('1546-QQ2', 'Hrd. cloth, 1/4-in., 2x50', '11-Mar-2018', 15, 8, 39.95, 0.00, NULL);
INSERT INTO PRODUCT VALUES('19-RSL', 'B+D cordless drill, 1/2-in', '20-Jan-2016', 80, 45, 69.99, 0.00, NULL);
INSERT INTO PRODUCT VALUES('LO-908', 'Claw hammer', '20-Jan-2016', 205, 175, 7.65, 0.00, NULL);
INSERT INTO PRODUCT VALUES('672/RT2', 'PVC Pipe, 3.5-in. 8-ft.', '20-Feb-2016', 25, 5, 5.63, 0.00, NULL);
INSERT INTO PRODUCT VALUES('XUM-029', '1.25-in. metal screw, 25', '01-Mar-2016', 48, 21, 8.95, 0.00, NULL);

SELECT *
FROM PRODUCT;

SELECT P_DESCRIPTION, P_INDATE, P_PRICE, V_CODE
FROM PRODUCT
WHERE V_CODE = 21225;

SELECT *
FROM PRODUCT
WHERE V_CODE <> 21300;

SELECT *
FROM PRODUCT
WHERE V_CODE != 21300;

SELECT *
FROM PRODUCT
WHERE P_PRICE <= 10;

SELECT *
FROM PRODUCT
WHERE P_CODE < '1558-QWI';

SELECT * 
FROM PRODUCT
WHERE P_INDATE >= '20-Jan-2016';

SELECT P_CODE, P_DESCRIPTION, P_INDATE, P_QOH, P_MIN, P_PRICE, P_DISCOUNT, V_CODE, P_QOH*P_PRICE AS INVENTORY_VALUE
FROM PRODUCT;